enum RequestStatus {
  IDLE,
  SUCCESS,
  LOADING,
  NO_CONNECTION,
  CONNECTION_ERROR,
  FAIL,
  UNAUTHORIZED,
  INTERNAL_SERVER_ERROR,
  UNPROCESSABLE_ENTITY,
  NOT_FOUND,
  TIME_OUT,
  BAD_REQUEST,
}